[target.x86_64-unknown-linux-gnu]
linker = "/usr/lib/llvm-14/bin/clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/mold"]
#rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/mold", "-C", "embed-bitcode=no"]

[build]
incremental = true  
target-dir = "/home/bas/.cache/cargo/target"
rustc-wrapper = "/home/bas/.cargo/bin/sccache"

[alias]
b = "build"
c = "check"
t = "test --tests"
r = "run"
rr = "run --release"
xv = "xtask validate"
xc = "xtask ci"
xdb = "xtask ci --only-setup-db -c"
x = "xtask"
