#!/bin/sh

[ -f $HOME/.profile ] && $HOME/.profile
# Make sure this is before the 'exec' command or it won't be sourced.
[ -f /etc/xprofile ] && . /etc/xprofile
[ -f $HOME/.xprofile ] && . $HOME/.xprofile
exec dbus-launch awesome $@
