colorscheme gruvbox-dark
set-option global startup_info_version 99999999
set-option global tabstop 4
set-option global indentwidth 4
set-option global scrolloff 5,1
set-option global grepcmd 'rg --column'
set-option global completers filename word=all
set-option -add global matching_pairs ‹ › « » “ ” ‘ ’
set-option global autowrap_column 78
hook global WinCreate .* %{ autowrap-enable }

hook global RegisterModified '"' %{ nop %sh{
  printf %s "$kak_main_reg_dquote" | xsel --input --clipboard
}}

map global user P '!xsel --output --clipboard<ret>'
map global user p '<a-!>xsel --output --clipboard<ret>'
map global user R '|xsel --output --clipboard<ret>'
